### ISSUE TITLE
Styling the map

### ISSUE THREAD

**Issue by ergunpp** [VictorCazanave/react-svg-map#51]
Hi,
I am trying to change the colors on the map, but whenever I set a custom locationClassName the clicked countries are surrounded with a large rectangle instead of the country borders.
How is it possible to style colours etc without changing the functionality of the map?

**Comment by VictorCazanave** [comment]
Hello,
I think the rectangle around the clicked location is due to the default styles of the browser when an element is focused.
You can disable it with `:focus { outline: 0; }`, but you should use another way to indicate which element is focused for accessibility reasons.
[Here](https://github.com/VictorCazanave/react-svg-map/blob/master/src/svg-map.scss#L16) is how it is done in the default provided styles.

**Comment by VictorCazanave** [comment]
@ergunpp if your issue is not fixed, feel free to re-open it.
